dynamic:
  cluster_id: default-cluster
  topic: exp-dynamic-r4
  stream_pattern: "^exp-wjh.*$"
  bootstrap_servers: localhost:9092
  emit_interval_ms: 5
  parallelism: 1
  discovery_interval_ms: 2000
  route_map:
    route-a:
      cluster_id: default-cluster
      bootstrap_servers: localhost:9092
      topic_regex: "^exp-dynamic-c$"
    route-b:
      cluster_id: default-cluster
      bootstrap_servers: localhost:9092
      topic_regex: "^exp-dynamic-d$"
    route-c:
      cluster_id: default-cluster
      bootstrap_servers: localhost:9092
      topic_regex: "^exp-dynamic-e$"
    route-d:
      cluster_id: default-cluster
      bootstrap_servers: localhost:9092
      topic_regex: "^exp-dynamic-f$"
