<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.apache.flink.dynamic</groupId>
    <artifactId>dynamic-kafka-sink-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Dynamic Kafka Sink Parent</name>

    <modules>
        <module>dynamic-kafka-sink-connector</module>
        <module>dynamic-kafka-sink-app</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <flink.version>2.1.0</flink.version>
        <kafka.version>4.2.0</kafka.version>
        <jackson.version>2.18.2</jackson.version>
        <commons-lang3.version>3.18.0</commons-lang3.version>
        <slf4j.version>1.7.36</slf4j.version>
        <log4j.version>2.25.0</log4j.version>
    </properties>
</project>
